version: 2.1
orbs:
  windows: circleci/windows@2.4.1

jobs:
  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: go version
      - run: go test ./...
  test-windows:
    executor:
      name: windows/default
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: go version
      - run: go test ./...

workflows:
  version: 2
  test:
    jobs:
      - test
      - test-windows
